YOUR_BOT_TOKEN = "MTQxNDcxNjAyNDEyNDg3MDgyNw.Gg_5Em.zoFJDcELxnY8PoJiNNFTXNvik7DFJtx4TRt4ew"


YOUR_API_KEY = "AIzaSyC49f3YLw89eMT3TPTCxfyLj3IPt4EcoOA"
## YOUR_API_KEY = "St859izsQfBkDWYPWVuz3aOqFfyNIQDC"